
export const links = [
    'https://drive.google.com/file/d/1lnS9EA-hkGY2AfzGeVsp9iRRASrwk_L3/view?usp=sharing',
    'https://drive.google.com/file/d/1Bxob7XsQdzNw-n0uhmjRFZKMFsvFoM79/view?usp=sharing',
    'https://drive.google.com/file/d/1nxTEuK34Pm9NHSAdRaPMujy4CmomDGzK/view?usp=sharing',
    'https://drive.google.com/file/d/1zh27_NXLzzTF-6B5PvbGLWdakpKth-ZF/view?usp=sharing',
    'https://drive.google.com/file/d/1GX-2TisTS1NNeQPSRq_CPCPI3YaBufHy/view?usp=sharing',
    'https://drive.google.com/file/d/1tdukoeRI2YrQcHkZSor7Y3kk0a-zEaHY/view?usp=sharing',
    'https://drive.google.com/file/d/1t8vfZSTFKQl082L5BWCZfAYifCwId0ZY/view?usp=sharing',
    'https://drive.google.com/file/d/1W0MDF748YK5UBL_AnVVTvcOY16KMHpF4/view?usp=sharing',
    'https://drive.google.com/file/d/1-h5-EkyBgAMbze6VpiYPrCO4V3k7wvd3/view?usp=sharing',
    'https://drive.google.com/file/d/1uRvKj5relTqs5g-up85_GxQfTGtvvkP6/view?usp=sharing',
    'https://drive.google.com/file/d/1kTZBCiTlohb8UXO5RFYSH_VVxMwYoVn1/view?usp=sharing',
    'https://drive.google.com/file/d/10S6lZaHR5csJnsFiUxbLeogu9DtbY448/view?usp=sharing',
    'https://drive.google.com/file/d/1vv87S85s3KrFdy20XXAbKLo_NtL6hMmd/view?usp=sharing',
    'https://drive.google.com/file/d/1pp0MnHfcexVzo4WXYK7CQP4XMAUYglYh/view?usp=sharing',
    'https://drive.google.com/file/d/1fBKvPIfkFnoOrgCtStFjl4WA1lfEtnIk/view?usp=sharing',
    'https://drive.google.com/file/d/1DqNm6hn6A0CQgRXOrMx3K4iFetdNDWN1/view?usp=sharing',
    'https://drive.google.com/file/d/1augASDeWk1MNABHf7FTEFdBgYZEbYkuu/view?usp=sharing',
    'https://drive.google.com/file/d/1uBxRpGzsoB1Fe73odSU0ZKPIaK7wXtXU/view?usp=sharing',
    'https://drive.google.com/file/d/1Mxg9TkDfmwFcR_LMUGFo6viZl01F7nOV/view?usp=sharing',
    'https://drive.google.com/file/d/1zZHqIq-SnmQE3ArBgs0RbSvYioeQdc6f/view?usp=sharing',
    'https://drive.google.com/file/d/15mXJKlnzK3z8q7EJI5D_ZH5wq8sxvPNc/view?usp=sharing',
    'https://drive.google.com/file/d/1DbSq1QgMKPxJvddxlx3DJwJAXgvsyYCr/view?usp=sharing',
    'https://drive.google.com/file/d/1_skuoAVdMCtQv9fMn5ZMJp9UoHiYRNhD/view?usp=sharing',
    'https://drive.google.com/file/d/12KotLz2gXpkLge0dJsVa6p7IWIxyhBJ3/view?usp=sharing',
    'https://drive.google.com/file/d/1GOHFQShckrCpMM74WBJeZ_M-J1yfeRxw/view?usp=sharing',
    'https://drive.google.com/file/d/15pOJ6FyS0rMjim1ewizWtQ2LpqLKoY9h/view?usp=sharing',
    'https://drive.google.com/file/d/1OeXIR1fC3MI_kJ-UYvT0se70fPVS85iz/view?usp=sharing',
    'https://drive.google.com/file/d/1i4JMiQ-FeAuAcnSH9PgvGA3-c3C1qJJU/view?usp=sharing',
    'https://drive.google.com/file/d/1Le_qZDOx_BIZybmMdhEds4qjY6no_ghc/view?usp=sharing',
    'https://drive.google.com/file/d/1Yrn_Jt4dP9RN7N7WU7A1xMDNTD6L3glG/view?usp=sharing',
    'https://drive.google.com/file/d/1S2730Zq2RggpW1Ek3ZSMy4GKFWyUVyJA/view?usp=sharing',
    'https://drive.google.com/file/d/1c-LVv4t-49X3LC4WuQqcrBspRey5HGtA/view?usp=sharing',
    'https://drive.google.com/file/d/1DRwj-0sf7Uu8yW-ATcmLm1QoUIw-D4v2/view?usp=sharing',
    'https://drive.google.com/file/d/1oO6DDUt_Q7UVusVzqUUwqwXLKXvCRBvW/view?usp=sharing',
    'https://drive.google.com/file/d/1pK_CNwth0J9C_snShHlhxJYJIAI2dYzH/view?usp=sharing',
    'https://drive.google.com/file/d/1Qo6an11mMQIpfB4YmoXtzjevOSP--IvW/view?usp=sharing',
    'https://drive.google.com/file/d/1F7xywQ9HumHDpsIyyJQ-Nhuhzy-gxyBZ/view?usp=sharing',
    'https://drive.google.com/file/d/1MwGixvBs5HlcrVlQYH_dxb9kXlG9wm6Z/view?usp=sharing',
    'https://drive.google.com/file/d/1c7H6bxp2OTBG8qwGAvQ9zhXLdoXqeiO7/view?usp=sharing',

]


export const nameArray = [
    'Oh My Kadavule',
    'redemption day',
    'The Kings Man',
    'Without Remorse',
    'John wick',
    'The Equalizer 2',
    'The Equalizer',
    'The magnificent seven',
    'The Adam Project',
    'Nobody',
    'Sonic the Hedgehog 2',
    'Sarkaru Vaari Paata',
    'Deep water',
    "Aquaman",
    "Eternals",
    "Black Widow",
    "Avengers Infinity War",
    "Venom Let There Be Carnage",
    "Shang-Chi And The Legend Of The Ten Rings",
    'American Psycho',
    'Black Hawk Down ',
    'Dune ',
    'House of Gucci ',
    'No Time to Die ',
    'Red Notice 2021 ',
    'The Kissing Booth ',
    'The Kissing Booth 2 ',
    'The Kissing Booth 3 ',
    'The Contractor 2022 ',
    'Wyrmwood Apocalypse ',
    'KGF Chapter 2 ',
    'Bachchhan Paandey ',
    ' The Last Duel ',
    'Beast (2022) ',
    'Doctor Strange In The Multiverse of Madness',
    'The Northman',
    'Ambulance',
    'Fantastic Beasts: The Secrets of Dumbledore',
    'Radhe shyam',

];
